config/routes.rb
Rails.application.routes.draw do
  root    'welcome#index'
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'


  resources :listeners do
    resources :checkins
  end

  get     '/:uuid', to: 'listeners#check_in'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :listener
end

app/models/listener.rb
class Listener < ApplicationRecord
  belongs_to :user
  has_many :checkins, dependent: :destroy
  validates :title, presence: true
  validates :interval, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :listeners
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  def create
    @listener = Listener.find(params[:listener_id])
    @checkin = @listener.checkins.create(checkin_params)
    redirect_to listener_path(@listener)
  end

  private
    def checkin_params
      params.require(:checkin).permit(:note)
    end
end

app/controllers/listeners_controller.rb
require 'securerandom'

class ListenersController < ApplicationController
    def index
        @listeners = Listener.all
    end

    def show
        @listener = Listener.find(params[:id])
    end

    def new
        @listener = Listener.new
    end

    def edit
        @listener = Listener.find(params[:id])
    end

    def create
        @listener = Listener.new(listener_params)
        @listener.uuid = SecureRandom.uuid
        @listener.url = "https://www.chaseslisteners.com/#{SecureRandom.hex}"
        @listener.isCheckedIn = false
        @listener.isVerified = false

        if @listener.save
            redirect_to @listener
        else
            render 'new'
        end
    end

    def update
        @listener = Listener.find(params[:id])

        if @listener.update(listener_params)
            redirect_to @listener
        else
            render 'edit'
        end
    end

    def destroy
        @listener = Listener.find(params[:id])
        @listener.destroy

        redirect_to listeners_path
    end

    def check_in
      @listener = Listener.find_by uuid: params[:uuid]
      @listener.isCheckedIn = true
      @listener.save
      redirect_to @listener
    end

    private
        def listener_params
            params.require(:listener).permit(:title, :interval, :notes)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user): forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Snitch App"
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/listeners_helper.rb
module ListenersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?
    user == current_user
  end

  # Returns the current logged in user, if any
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snitch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listeners/_form.html.erb
<%= form_with(model: @listener, local: true) do |form| %>

    <% if @listener.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@listener.errors.count, "error") %>
                prohibited this article from being saved:
            </h2>
            <ul>
                <% @listener.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>

    <p>
        <%= form.label :interval %><br>
        <%= form.radio_button :interval, "hourly" %>
        <%= form.label :interval_hourly, "Hourly" %><br>
        <%= form.radio_button :interval, "daily" %>
        <%= form.label :interval_daily, "Daily" %><br>
        <%= form.radio_button :interval, "weekly" %>
        <%= form.label :interval_weekly, "Weekly" %><br>
        <%= form.radio_button :interval, "monthly" %>
        <%= form.label :interval_monthly, "Monthly" %><br>
    </p>

    <p>
        <%= form.label :notes %><br>
        <%= form.text_area :notes %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/listeners/edit.html.erb
<h1>Edit listener</h1>

<%= render 'form' %>

<%= link_to 'Back', listeners_path %>

app/views/listeners/index.html.erb
<h1>Listing Listeners</h1>

<%= link_to 'New Listener', new_listener_path %>

<table>
    <tr>
        <th>Title</th>
        <th>Interval</th>
        <th></th>
    </tr>

    <% @listeners.each do |listener| %>
        <tr>
            <td><%= listener.title %></td>
            <td><%= listener.interval %></td>
            <td><%= link_to 'Show', listener_path(listener) %></td>
            <td><%= link_to 'Edit', edit_listener_path(listener)%></td>
            <td><%= link_to 'Delete', listener_path(listener),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
</table>

app/views/listeners/new.html.erb
<h1>New Listener</h1>

<%= render 'form' %>

<%= link_to 'Back',listeners_path %>

app/views/listeners/show.html.erb
<h1><%= @listener.title %></h1>

<%= !@listener.isVerified ? "Not Verified" : "" %>

<p>
    <strong>URL</strong>
    <%= @listener.url %>
</p>

<p>
    <strong>UUID</strong>
    <%= @listener.uuid %>
</p>

<p>
    <strong>Interval</strong>
    <%= @listener.interval %>
</p>

<p>
    <strong>Checked In?</strong>
    <%= @listener.isCheckedIn %>
</p>

<p>
    <strong>Notes</strong>
    <%= @listener.notes %>
</p>

<h2>Checkins</h2>
<% @listener.checkins.each do |checkin| %>
    <p>
        <strong>Checkin Time</strong>
        <%= checkin.created_at %>
    </p>

    <% if checkin.note != "" %>
    <p>
        &emsp;<strong>Note</strong>
        <%= checkin.note %>
    </p>
    <% end %>
<% end %>

<h2>Add a checkin:</h2>
<%= form_with(model: [ @listener, @listener.checkins.build ],
local: true) do |form| %>
    <p>
        <%= form.label :note %><br>
        <%= form.text_area :note %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

<%= link_to 'Edit', edit_listener_path(@listener) %>
<%= link_to 'Back', listeners_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    The form contains <%= pluralize(@user.errors.count, "error") %>.
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/snitches/new.html.erb
<h1>New Snitch</h1>
<%= form_with scope: :snitch, local: true do |form| %>
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title%>
    </p>

    <p>
        <%= form.label :interval %><br>
        <%= radio_button_tag(:interval, "hourly") %>
        <%= label_tag(:interval_hourly, "Hourly") %><br>
        <%= radio_button_tag(:interval, "daily") %>
        <%= label_tag(:interval_daily, "Daily") %><br>
        <%= radio_button_tag(:interval, "weekly") %>
        <%= label_tag(:interval_weekly, "Weekly") %><br>
        <%= radio_button_tag(:interval, "monthly") %>
        <%= label_tag(:interval_monthly, "Monthly") %><br>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes" %>
    <% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Create my account" %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Station</h1>
<h2>User Profile</h2>
<%= @user.name %>, <%= @user.email %>

app/views/welcome/index.html.erb
<h1>Welcome to My Listener</h1>
<%= link_to 'My Listener', controller: 'listeners' %>